version: '3.8'

services:
  veloclub-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veloclub-website
    restart: unless-stopped
    ports:
      - "4000:80"
    networks:
      - web

networks:
  web:
    external: true